
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cico
    username: postgres
    password: soniya@4752


    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8899
