
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cico

    username: bishal
    password: 1111


    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8899
